package org.firstinspires.ftc.teamcode.utils.gamepad;

public enum PAD_KEY {
    a,
    b,
    back,
    dpad_down,
    dpad_left,
    dpad_right,
    dpad_up,
    guide,
    left_bumper,
    left_stick_button,
    right_bumper,
    right_stick_button,
    start,
    x,
    y,
    left_trigger,
    right_trigger,
    left_stick_x,
    left_stick_y,
    right_stick_x,
    right_stick_y,
}
